### ISSUE TITLE
Passport 3.0

### ISSUE THREAD

**Issue by Dolaned** [mirkco/Laravel-Passport-Facebook-Login#3]
Hey Mate will this package be updated for passport 3.0, id like to help but don't know where to start.

**Comment by danjdewhurst** [comment]
I've updated it for 3.0 here https://github.com/danjdewhurst/Laravel-Passport-Facebook-Login - if that helps at all.

**Comment by Dolaned** [comment]
I like your version for the updated laravel passport 3.0, might make the user models dynamic. thanks mate!

**Comment by se1exin** [comment]
Hi @danjdewhurst, looks like your version is more up to date and flexible - do you want to take over the package?

Unfortunately we don't have a heap of time to maintain this one, so I'm happy to update the readme to point to your repo as the preferred version if you'd like?

**Comment by danjdewhurst** [comment]
@se1exin, yeah sure. I can take it over.  Thanks.

**Comment by se1exin** [comment]
@danjdewhurst cheers
